// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnxbqdwlqgcukwlfgclc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBueGJxZHdscWdjdWt3bGZnY2xjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNzUzNzUsImV4cCI6MjA3MDY1MTM3NX0.hW9wBpRkqMmrapf-QEhl_DKb9p4kgzSXYqnitB99o1w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});